-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMpRoGcfDK2Jla3y3
PhgKMtOlOdBOQOKJba93PRK5YkWgCgYIKoZIzj0DAQehRANCAAT2PhOU9uqKL+5H
NZO+qHOPc8mZv0phDeN3LHLbciHYiVb3s3ZEJma+AqgN5LXbVLT0MbqV1nm5VfC8
aJLdYYFn
-----END PRIVATE KEY-----